name: YamidaCore
main: dev.airdead.yamidacore.YamidaCore
version: 1.0
author: Yamida
description: Core plugin for Yamida's server.
api-version: 1.17

commands:
  modules:
    description: Change modules settings.
  inspect:
    description: Inspect a player.
    aliases:
      - ispect
      - whois