name: YamidaCore
main: dev.airdead.yamidacore.YamidaCore
version: 1.0
author: Yamida
description: Core plugin for Yamida's server.
api-version: 1.17

commands:
  try:
    description: Try a action.
  pm:
    description: "Отправить личное сообщение игроку"
    usage: "/pm <ник> <сообщение>"
    aliases: []
  reply:
    description: "Ответить на личное сообщение"
    usage: "/reply <сообщение>"
    aliases:
        - r